//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellDataImporter.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WellDataImporter.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт данных по скважинам.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт в JSON.
        /// </summary>
        public static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить CSV.
        /// </summary>
        public static string BtnImport {
            get {
                return ResourceManager.GetString("BtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая глубина.
        /// </summary>
        public static string ColDepth {
            get {
                return ResourceManager.GetString("ColDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание ошибки.
        /// </summary>
        public static string ColError {
            get {
                return ResourceManager.GetString("ColError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервалы.
        /// </summary>
        public static string ColIntervals {
            get {
                return ResourceManager.GetString("ColIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка CSV.
        /// </summary>
        public static string ColLine {
            get {
                return ResourceManager.GetString("ColLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя пористость.
        /// </summary>
        public static string ColPorosity {
            get {
                return ResourceManager.GetString("ColPorosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основная порода.
        /// </summary>
        public static string ColRock {
            get {
                return ResourceManager.GetString("ColRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WellId.
        /// </summary>
        public static string ColWellId {
            get {
                return ResourceManager.GetString("ColWellId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DepthFrom должен быть меньше DepthTo.
        /// </summary>
        public static string ErrorDepthFromDepthTo {
            get {
                return ResourceManager.GetString("ErrorDepthFromDepthTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DepthFrom не может быть меньше 0.
        /// </summary>
        public static string ErrorDepthFromZero {
            get {
                return ResourceManager.GetString("ErrorDepthFromZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружено пересечение интервалов.
        /// </summary>
        public static string ErrorInterval {
            get {
                return ResourceManager.GetString("ErrorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат строки.
        /// </summary>
        public static string ErrorLengthLineFile {
            get {
                return ResourceManager.GetString("ErrorLengthLineFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порода (Rock) не должна быть пустой.
        /// </summary>
        public static string ErrorNullRock {
            get {
                return ResourceManager.GetString("ErrorNullRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка конвертации числовых данных.
        /// </summary>
        public static string ErrorParseNumber {
            get {
                return ResourceManager.GetString("ErrorParseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пористость (Porosity) должна быть в диапазоне [0..1].
        /// </summary>
        public static string ErrorPorosity01 {
            get {
                return ResourceManager.GetString("ErrorPorosity01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения файла: {0}.
        /// </summary>
        public static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WellId пустой не должна быть пустой.
        /// </summary>
        public static string ErrorWellIdNull {
            get {
                return ResourceManager.GetString("ErrorWellIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список найденных ошибок:.
        /// </summary>
        public static string LblErrorList {
            get {
                return ResourceManager.GetString("LblErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные успешно экспортированы!.
        /// </summary>
        public static string MsgExportSuccess {
            get {
                return ResourceManager.GetString("MsgExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт данных....
        /// </summary>
        public static string StatusExporting {
            get {
                return ResourceManager.GetString("StatusExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт успешно завершен.
        /// </summary>
        public static string StatusExportingDone {
            get {
                return ResourceManager.GetString("StatusExportingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка экспорта.
        /// </summary>
        public static string StatusExportingError {
            get {
                return ResourceManager.GetString("StatusExportingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидание загрузки файла....
        /// </summary>
        public static string StatusIdle {
            get {
                return ResourceManager.GetString("StatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка и обработка файла....
        /// </summary>
        public static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработано скважин: {0}. Ошибок: {1}.
        /// </summary>
        public static string StatusReadDone {
            get {
                return ResourceManager.GetString("StatusReadDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка при чтении файла.
        /// </summary>
        public static string StatusReadError {
            get {
                return ResourceManager.GetString("StatusReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Глубина не может быть отрицательной.
        /// </summary>
        public static string VldDepthNeg {
            get {
                return ResourceManager.GetString("VldDepthNeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DepthFrom должен быть меньше DepthTo.
        /// </summary>
        public static string VldDepthRange {
            get {
                return ResourceManager.GetString("VldDepthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название породы не может быть пустым.
        /// </summary>
        public static string VldEmptyRock {
            get {
                return ResourceManager.GetString("VldEmptyRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружено пересечение интервалов.
        /// </summary>
        public static string VldOverlap {
            get {
                return ResourceManager.GetString("VldOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка преобразования данных в строке.
        /// </summary>
        public static string VldParseErr {
            get {
                return ResourceManager.GetString("VldParseErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пористость должна быть в диапазоне [0..1].
        /// </summary>
        public static string VldPorosity {
            get {
                return ResourceManager.GetString("VldPorosity", resourceCulture);
            }
        }
    }
}
